# Generated by Django 3.1.12 on 2022-03-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='last_time',
            new_name='last_name',
        ),
    ]
